name: pyco_test_tony
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  chopper: ^3.0.0
  material_design_icons_flutter: ^2.7.94
  built_value: ^6.7.0
  sqflite: ^1.2.0
  image_downloader: ^0.19.1
  permission_handler: ^4.2.0
  connectivity: ^0.4.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.0
  build_runner: ^1.6.7
  built_value_generator: ^6.7.0
    
flutter:

  uses-material-design: true
